name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - collaborative-circom-v[0-9]+.*

jobs:
  upload-assets:
    runs-on: [arc-runner-set]
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: co-circom
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
